language: ruby
rvm:
  - 2.4.1

#https://docs.travis-ci.com/user/database-setup/#PostgreSQL
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database "radio-logger_test";' -U postgres
  - RAILS_ENV=test bin/rake --trace db:migrate

script: bin/rake spec && bundle exec rubocop -D -c .rubocop.yml
